# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"AbstractCalculator": "00_calculators.ipynb",
         "TestCalculator": "00_calculators.ipynb",
         "AbstractOperation": "01_operators.ipynb",
         "EquationOp": "01_operators.ipynb",
         "AggregationOp": "01_operators.ipynb",
         "ClipOp": "01_operators.ipynb",
         "AbstractNormative": "01_operators.ipynb",
         "MeanStdNormative": "01_operators.ipynb",
         "NormativeLookupOp": "01_operators.ipynb",
         "BinnedScalingOp": "01_operators.ipynb",
         "CategoricalOp": "01_operators.ipynb",
         "EquationFilterOp": "01_operators.ipynb",
         "LookupNormative": "01_operators.ipynb",
         "MultiLookupOp": "01_operators.ipynb",
         "HEATON_MAPPINGS": "01_operators.ipynb",
         "quantile_df": "03_domains.ipynb",
         "AbstractDomain": "03_domains.ipynb",
         "quantile_transform_placeholders": "03_domains.ipynb",
         "MemoryDomain": "03_domains.ipynb",
         "MotorDomain": "03_domains.ipynb",
         "ExecutiveFunctionDomain": "03_domains.ipynb",
         "AttentionDomain": "03_domains.ipynb",
         "LanguageDomain": "03_domains.ipynb",
         "VisuoSpatialDomain": "03_domains.ipynb",
         "FieldMapper": "04_field_mapping.ipynb",
         "create_scaling": "09_batteries.ipynb",
         "check_battery": "09_batteries.ipynb",
         "AbstractBattery": "09_batteries.ipynb",
         "BVMTBattery": "09_batteries.ipynb",
         "HVLTBattery": "09_batteries.ipynb",
         "SENASWordlistBattery": "09_batteries.ipynb",
         "LetterFluencyBattery": "09_batteries.ipynb",
         "CategoryFluencyAnimalsBattery": "09_batteries.ipynb",
         "BNT30Battery": "09_batteries.ipynb",
         "ClockDrawingBattery": "09_batteries.ipynb",
         "ROCFBattery": "09_batteries.ipynb",
         "GroovedPegBoardBattery": "09_batteries.ipynb",
         "TrailABattery": "09_batteries.ipynb",
         "TrailBBattery": "09_batteries.ipynb",
         "WAIS4DigitSymbolBattery": "09_batteries.ipynb",
         "mWCSTBattery": "09_batteries.ipynb",
         "StroopBattery": "09_batteries.ipynb"}

modules = ["calculators.py",
           "operators.py",
           "motivating_example.py",
           "domains.py",
           "field_mapping.py",
           "explorations.py",
           "batteries.py"]

doc_url = "https://judowill.github.io/autoneuro/"

git_url = "https://github.com/judowill/autoneuro/tree/main/"

def custom_doc_links(name): return None
