# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"AbstractCalculator": "00_calculators.ipynb",
         "TestCalculator": "00_calculators.ipynb",
         "AbstractOperation": "01_operators.ipynb",
         "EquationOp": "01_operators.ipynb",
         "AggregationOp": "01_operators.ipynb",
         "ClipOp": "01_operators.ipynb",
         "NormativeLookupOp": "01_operators.ipynb",
         "BinnedScalingOp": "01_operators.ipynb",
         "CategoricalOp": "01_operators.ipynb",
         "EquationFilterOp": "01_operators.ipynb",
         "AbstractDomain": "03_domains.ipynb",
         "MemoryDomain": "03_domains.ipynb",
         "ExecutiveFunctionDomain": "03_domains.ipynb"}

modules = ["calculators.py",
           "operators.py",
           "motivating_example.py",
           "domains.py"]

doc_url = "https://judowill.github.io/autoneuro/"

git_url = "https://github.com/judowill/autoneuro/tree/main/"

def custom_doc_links(name): return None
