# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"LookupNormalTransform": "00_core.ipynb",
         "FILTER_MAPPINGS": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://judowill.github.io/autoneuro/"

git_url = "https://github.com/judowill/autoneuro/tree/main/"

def custom_doc_links(name): return None
